// Configuration constants for the NARS system
export const PRIORITY = {
    CONFIDENCE_MULTIPLIER: 0.3,
    GOAL_BOOST: 0.2,
    QUESTION_BOOST: 0.1
};

export const LM = {
    DEFAULT_TEMPERATURE: 0.7,
    DEFAULT_MAX_TOKENS: 1000,
    MOCK_RESPONSE_TOKENS: 150,
    MOCK_CONTENT_TRUNCATION: 100
};

export const TRUTH = {
    DEFAULT_FREQUENCY: 0.5,
    MAX_CONFIDENCE: 1.0,
    MIN_PRIORITY: 0.0,
    MAX_PRIORITY: 1.0
};

export const SYSTEM = {
    DEFAULT_CYCLE_DELAY: 100,
    DEFAULT_PRIORITY: 0.5,
    METRIC_HISTORY_LIMIT: 1000
};