import React, { useState } from 'react';
import { DndContext, closestCorners } from '@dnd-kit/core';
import { arrayMove, SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { getItemIcon } from '../utils/common';
import {
  createTaskItemStyle,
  createPriorityIndicatorStyle,
  createTaskContentStyle,
  createTaskControlsStyle,
  createTaskDetailsStyle,
  createButtonGroupStyle,
  createListContainerStyle,
  createScrollableContainerStyle,
  createPanelHeaderStyle,
  createEmptyState
} from '../utils/componentPatterns';

const SortableTaskItem = ({ task, index, onPriorityChange, onDeleteTask }) => {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: task.id || index });
  const [isExpanded, setIsExpanded] = useState(false);

  const priority = task.priority || 0.5;
  const itemStyle = createTaskItemStyle(isExpanded, isDragging, priority);
  const controlsStyle = createTaskControlsStyle();
  const detailsStyle = createTaskDetailsStyle();

  return (
    <div
      ref={setNodeRef}
      style={itemStyle}
      {...attributes}
      {...listeners}
      onClick={() => setIsExpanded(!isExpanded)}
    >
      <span style={createPriorityIndicatorStyle(priority)}>
        {getItemIcon(task.type)}
      </span>

      <div style={createTaskContentStyle()}>
        <div style={createTaskContentStyle().title}>
          {task.content || task.id || `Task ${index + 1}`}
        </div>
      </div>

      <div style={controlsStyle}>
        <span style={controlsStyle.priority}>
          {priority.toFixed(2)}
        </span>

        <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={priority}
          onChange={e => onPriorityChange(task, parseFloat(e.target.value))}
          style={controlsStyle.slider}
          title="Drag to reprioritize"
        />

        <button
          onClick={e => (e.stopPropagation(), setIsExpanded(!isExpanded))}
          style={{
            ...controlsStyle.toggle,
            backgroundColor: isExpanded ? '#0d6efd' : '#6c757d',
            color: 'white'
          }}
        >
          ⋯
        </button>
      </div>

      {isExpanded && (
        <div style={detailsStyle}>
          <div style={detailsStyle.header}>
            <h4 style={detailsStyle.header.title}>Task Details</h4>
            <button onClick={() => setIsExpanded(false)} style={detailsStyle.header.close}>
              ×
            </button>
          </div>

          <div style={detailsStyle.grid}>
            <div><strong>ID:</strong> {task.id || 'N/A'}</div>
            <div><strong>Type:</strong> {task.type || 'N/A'}</div>
            <div><strong>Status:</strong> {task.status || 'N/A'}</div>
            <div><strong>Priority:</strong> {priority.toFixed(3)}</div>
            <div><strong>Created:</strong> {task.created || 'N/A'}</div>
            <div><strong>Content:</strong> {task.content || 'N/A'}</div>
          </div>

          <div style={detailsStyle.actions}>
            {[
              { label: '▶️ Execute', action: () => console.log('Execute task:', task.id) },
              { label: '🗑️ Delete', action: () => onDeleteTask(task) },
              { label: '⬆️ Up Priority', action: () => onPriorityChange(task, Math.min(1, priority + 0.1)) }
            ].map((btn, i) => (
              <button key={i} style={detailsStyle.actions.button} onClick={btn.action}>
                {btn.label}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

const TasksPanel = ({ tasks = [], memoryTasks = [], onUpdateTask, onDeleteTask }) => {
  const [displayTasks, setDisplayTasks] = useState(memoryTasks.length > 0 ? memoryTasks : tasks || []);

  React.useEffect(() => {
    setDisplayTasks(memoryTasks.length > 0 ? memoryTasks : tasks || []);
  }, [memoryTasks, tasks]);

  const handlePriorityChange = (task, newPriority) => {
    onUpdateTask?.({ ...task, priority: newPriority, lastModified: Date.now() });
  };

  const handleDeleteTask = (task) => {
    onDeleteTask?.(task);
  };

  const handleDragEnd = (event) => {
    const { active, over } = event;
    if (active.id === over.id) return;

    const oldIndex = displayTasks.findIndex(task => task.id === active.id);
    const newIndex = displayTasks.findIndex(task => task.id === over.id);

    (oldIndex !== -1 && newIndex !== -1) &&
      setDisplayTasks(arrayMove(displayTasks, oldIndex, newIndex));
  };

  const isMemoryMode = memoryTasks.length > 0;
  const emptyStateIcon = isMemoryMode ? '🧠' : '📋';
  const emptyStateTitle = isMemoryMode ? 'No derivations available' : 'No active tasks';
  const emptyStateSubtitle = isMemoryMode
    ? 'Derivations will appear here as they are generated by the reasoning system'
    : 'Tasks will appear here as they are created';

  return (
    <div className="tasks-tree" style={createListContainerStyle()}>
      <div style={createPanelHeaderStyle(`${isMemoryMode ? 'Derivations' : 'Active Tasks'} (${displayTasks.length})`)}>
        <span style={createPanelHeaderStyle().title}>{isMemoryMode ? 'Derivations' : 'Active Tasks'} ({displayTasks.length})</span>
      </div>

      <DndContext collisionDetection={closestCorners} onDragEnd={handleDragEnd}>
        <div style={createScrollableContainerStyle()}>
          <SortableContext items={displayTasks.map(t => t.id || displayTasks.indexOf(t))} strategy={verticalListSortingStrategy}>
            {displayTasks.length > 0 ? (
              displayTasks.map((task, index) => (
                <div key={`${task.id || index}-container`} style={{ position: 'relative' }}>
                  <SortableTaskItem
                    task={task}
                    index={index}
                    onPriorityChange={handlePriorityChange}
                    onDeleteTask={handleDeleteTask}
                  />
                </div>
              ))
            ) : (
              <div style={createEmptyState(emptyStateIcon, emptyStateTitle, emptyStateSubtitle)}>
                <div style={createEmptyState().content.icon}>{emptyStateIcon}</div>
                <div style={createEmptyState().content.title}>{emptyStateTitle}</div>
                <div style={createEmptyState().content.subtitle}>{emptyStateSubtitle}</div>
              </div>
            )}
          </SortableContext>
        </div>
      </DndContext>
    </div>
  );
};

export default TasksPanel;
