import React, { useState, useEffect } from 'react';
import SortablePanel from './base/SortablePanel';

// Task-specific expanded content renderer
const renderTaskExpandedContent = (task) => (
  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
    <div><strong>ID:</strong> {task.id || 'N/A'}</div>
    <div><strong>Type:</strong> {task.type || 'N/A'}</div>
    <div><strong>Status:</strong> {task.status || 'N/A'}</div>
    <div><strong>Priority:</strong> {(task.priority || 0).toFixed(3)}</div>
    <div><strong>Created:</strong> {task.created || 'N/A'}</div>
    <div><strong>Content:</strong> {task.content || 'N/A'}</div>
  </div>
);

const TasksPanel = ({ tasks = [], memoryTasks = [], onUpdateTask, onDeleteTask }) => {
  // Use memoryTasks (derivations from Memory) if available, otherwise fall back to regular tasks
  const [displayTasks, setDisplayTasks] = useState(memoryTasks.length > 0 ? memoryTasks : tasks || []);

  useEffect(() => {
    // Prioritize memoryTasks (derivations) over regular tasks
    setDisplayTasks(memoryTasks.length > 0 ? memoryTasks : tasks || []);
  }, [memoryTasks, tasks]);

  const getPanelTitle = () => {
    const count = displayTasks.length;
    return memoryTasks.length > 0 ? `Derivations (${count})` : `Active Tasks (${count})`;
  };

  const getEmptyMessage = () => {
    return memoryTasks.length > 0 ? 'No derivations available' : 'No active tasks';
  };

  const getEmptyDescription = () => {
    return memoryTasks.length > 0
      ? 'Derivations will appear here as they are generated by the reasoning system'
      : 'Tasks will appear here as they are created';
  };

  return (
    <SortablePanel
      items={displayTasks}
      type="task"
      title={getPanelTitle()}
      emptyIcon="📋"
      emptyMessage={getEmptyMessage()}
      emptyDescription={getEmptyDescription()}
      onUpdateItem={onUpdateTask}
      onDeleteItem={onDeleteTask}
      renderExpandedContent={renderTaskExpandedContent}
    />
  );
};

export default TasksPanel;
