
import { createCore } from '../../core/createCore';

/**
 * This experimental test suite explores using an LM as an "ethical governor"
 * to ensure plans generated by NARS align with a set of core values.
 * Before executing a potentially sensitive plan, the system asks the LM for an
 * ethical evaluation, and the feedback can inhibit or alter the action.
 */
describe('Experimental: LM-driven Ethical Plan Evaluation', () => {

  it('should use the LM to block a plan that violates a core principle', async () => {
    const core = createCore();

    // 1. Define a core ethical principle in natural language.
    const ethicalPrinciples = [
      "Do not cause physical harm to living beings."
    ];
    core.setConfig('self.ethics.principles', ethicalPrinciples);

    // 2. NARS generates a plan to achieve a goal. The plan is logically valid but ethically problematic.
    const unethicalPlan = '(&/, open(cage), release(lion))';
    const goal = 'create(excitement)';
    await core.addInput(`(${unethicalPlan} ==> ${goal}).`);
    await core.addInput(`${goal}!`);

    // 3. A hypothetical "pre-execution hook" intercepts the plan.
    //    It sends the plan and the ethical principles to the LM for evaluation.
    //    LM Prompt (using a 'evaluatePlan' function):
    //    "Plan: 'Open the lion's cage and release it'.
    //     Principle: 'Do not cause physical harm to living beings.'
    //     Does this plan violate the principle? Answer with { 'violation': true/false, 'reason': '...' }"
    const evaluation = await core.self.evaluatePlan(unethicalPlan);

    // 4. The LM should identify a potential violation.
    expect(evaluation.violation).toBe(true);
    expect(evaluation.reason.toLowerCase()).toContain('potential harm');

    // 5. The system uses this feedback to create a new belief about the plan.
    //    This belief will be used by the reasoner to inhibit the plan's execution.
    await core.addInput(`(${unethicalPlan} ==> causes_harm).`);

    // 6. Verify the new belief exists, which effectively "taints" the unethical plan.
    const harmBelief = core.memory.getBelief(`(${unethicalPlan} ==> causes_harm)`);
    expect(harmBelief).toBeDefined();
    expect(harmBelief.truth.confidence).toBeGreaterThan(0.8);

    // The execution engine would then see that the plan leads to harm and would not execute it.
  });
});
